# Assignments
Design_Thinking_Project
| Assignment | Description  | Reflection |
| :-----: |  ------ | :-----: | 
| 1 | Assignment 1/Poster | Reflection 1 <br> I greatly admire Mr. Yee as my preferred speaker in this talk. His passion and dedication to his work are inspiring, driving him toward success. Embracing challenges as opportunities for continuous learning, he embodies the belief that education is a lifelong journey. I aim to emulate his approach. Furthermore, his insights on becoming a valuable employee resonate with me. Mr. Yee stresses the importance of personal development starting now, not just after graduation. He highlights self-learning as a crucial skill, recognizing that, in the professional realm, one often needs to rely on individual initiative. I hold these pieces of advice in high regard, recognizing them as key elements for my future success.| 
| 2 | Assignment 2/Video | Reflection 2 <br> The industry visit provided a refreshing change of pace, allowing me to spend time with classmates after a week of intensive studies. Besides enjoying ourselves while exploring, we also gained valuable insights into the inner workings of an IT office, such as UTM Digital. This experience holds significant benefits for me, as it was my first exposure to an office environment like this. It has fueled my determination to work diligently, aspiring to secure a position in a similarly positive office culture. The office's features and cutting-edge technologies I encountered during the visit have not only inspired me but also broadened my understanding of potential career paths. While I wasn't initially enthusiastic about this subject, the Industry Visit 1 has transformed my perspective, making me look forward to it more due to its engaging and practical activities. I anticipate learning and having fun in similar courses in the future. <br> Video Link <br> https://drive.google.com/drive/folders/1Dq5C8PDExWydHJ8A3ihGCFXFyW6USKns?usp=sharing | 
| 3 | Assignment 3/Report | Reflection 3 <br> Following this presentation, I now comprehend the significance of analytics and its pivotal role in the professional landscape. The realization that nearly everything around us stems from analytics is captivating, shedding light on its profound impact on the world. Prior to this talk, analytics was unfamiliar territory for me, and I lacked interest in the field. However, the industry talk has sparked a newfound curiosity and consideration for analytics as a potential career path. I appreciate UTM for providing me, as a first-year student, and others with the chance to gain real-world exposure, opening doors to career possibilities that I might not have discovered otherwise. | 
| 4 | Assignment 4/Newsletter | Reflection 4 <br> The visit proved to be a truly enlightening experience for me. Personally, I found the office space highly appealing due to its neat and clean layout, coupled with the provision of large monitors at each desk for individual use. Interacting with every member of the office provided valuable insights into their respective roles, and this face-to-face explanation was far more engaging than a virtual talk. The opportunity to freely roam the office and interact with its members, getting to know them better, stood out as my favorite part of the visit. The overall environment and culture of the office felt exceptionally comfortable. This experience has instilled in me a desire to work in a similar office setting like Clarity Techwork in the future.|
| 5 | Quiz/PC Assemble | Reflection Quiz <br> This activity is my most anticipated one, as I've always held an interest in PC building but lacked hands-on experience. I express gratitude to UTM for providing me with this valuable opportunity. The comprehensive explanations from both professors and assistants during the activity have significantly enhanced my understanding. Each step, whether it's disassembling or assembling the PC, is meticulously detailed. The enjoyable competition at the end, where groups compete to assemble the PC, adds an element of fun to the experience. Despite a quiz following the building session, it proved manageable due to the thorough explanations provided during the practical session. The quiz served as a helpful tool for reinforcing and retaining the knowledge gained. I am confident that, thanks to this exceptional learning opportunity, I'll be well-prepared to undertake PC building personally in the future.|
| 6 | Design Thinking  | Reflection <br> My goal in this course is to immerse myself in the professional field as much as possible. Unlike courses that focus solely on theoretical knowledge, TIS encourages practical learning by facilitating communication with experts in the field.<br> Engaging in this project has provided valuable insights into the fundamental aspects of developing a system independently. This hands-on experience will contribute to building a solid foundation for creating apps or websites in the future.<br> To unlock my full potential, active participation in extracurricular projects is crucial. While still in college, gaining hands-on experience is the most valuable asset, paving the way for achieving my desired goals.<br> Presentation Video Link <br> https://drive.google.com/file/d/1u7DF6dh4vOf2Ze3YrfGYCclLSXrBy08M/view?usp=sharing |
